server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan_db
    username: root
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
